export const pujaList = [
  {
    name: "Ganesh Puja",
    price: 999,
    rating: 4.8,
    totalBookings: 120,
    duration: "1 hour",
    img: "/images/ganesh.jpg",
  },
  {
    name: "Lakshmi Puja",
    price: 1499,
    rating: 4.9,
    totalBookings: 200,
    duration: "1.5 hours",
    img: "/images/lakshmi.jpg",
  },
  {
    name: "Satyanarayan Katha",
    price: 1999,
    rating: 4.7,
    totalBookings: 95,
    duration: "2 hours",
    img: "/images/satyanarayan.jpg",
  },
  {
    name: "Navagraha Puja",
    price: 2499,
    rating: 4.9,
    totalBookings: 150,
    duration: "2 hours",
    img: "/images/navagraha.jpg",
  },
  {
    name: "Maha Rudrabhishek",
    price: 2999,
    rating: 4.9,
    totalBookings: 80,
    duration: "2.5 hours",
    img: "/images/rudra.jpg",
  },
  {
    name: "Saraswati Puja",
    price: 1299,
    rating: 4.8,
    totalBookings: 110,
    duration: "1 hour",
    img: "/images/saraswati.jpg",
  },
  {
    name: "Durga Puja",
    price: 1999,
    rating: 4.9,
    totalBookings: 175,
    duration: "1.5 hours",
    img: "/images/durga.jpg",
  },
  {
    name: "Shivratri Puja",
    price: 2499,
    rating: 4.9,
    totalBookings: 130,
    duration: "2 hours",
    img: "/images/shivratri.jpg",
  },
  {
    name: "Vishnu Abhishek",
    price: 1799,
    rating: 4.7,
    totalBookings: 90,
    duration: "1.5 hours",
    img: "/images/vishnu.jpg",
  },
  {
    name: "Ayush Puja",
    price: 1599,
    rating: 4.6,
    totalBookings: 85,
    duration: "1 hour",
    img: "/images/ayush.jpg",
  },
];
